projects:
  movilsourcestock-dev:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
        apiId: kin4uk6sifegzeuxzx264mvubq
        maxDepth: 2
extensions:
  amplify:
    version: 3
